---

- name: Deploy 'petclinic'
  hosts: ubuntu
  become: yes
  vars:
    service_file: /etc/systemd/system/my-webapp-new.service
  tasks:

    - name: Check if service is installed
      stat:
        path: '{{ service_file }}'
      register: service_result
      
    - name: Stop service
      service:
        name: my-webapp-new
        state: stopped
        use: service
      when: service_result.stat.exists == True
      
    - name: Copy JAR file
      copy:
        src: ./spring-petclinic-main/target/spring-petclinic-2.4.2.jar
        dest: /home/vagrant
        
        
    - name: Copy service file
      copy:
        src: ./my-webapp-new.service
        dest: '{{ service_file }}'
        
    - name: Copy service execute .sh file
      copy:
        src: ./my-webapp-new-sh
        dest: /home/vagrant
        
    - name: Make service file executable
      file:
        path: '{{ service_file }}'
        mode: 755

    - name: Make service execute .sh file executable
      file:
        path: /home/vagrant/my-webapp-new-sh
        mode: u+x
        
    - name: Reload services
      systemd:
        daemon_reload: yes
  
    - name: Start service
      service:
        name: my-webapp-new
        state: started
        use: service
